# Generated by Django 3.0.7 on 2022-09-16 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('id_auxiliar', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='Historia_clinica',
            fields=[
                ('id_historia', models.AutoField(primary_key=True, serialize=False)),
                ('diagnostico', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=15)),
                ('especialidad', models.CharField(max_length=15)),
                ('registro', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('genero', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_nac', models.DateField()),
                ('direccion', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id_sug', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('id_historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalAPP.Historia_clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Signos_vitales',
            fields=[
                ('id_signos', models.AutoField(primary_key=True, serialize=False)),
                ('oximetria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('f_respiratoria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('f_cardiaca', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('p_arterial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('glicemias', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalAPP.Paciente')),
            ],
        ),
        migrations.AddField(
            model_name='historia_clinica',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalAPP.Paciente'),
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('genero', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=15)),
                ('parentesco', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=130)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalAPP.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id_signos', models.AutoField(primary_key=True, serialize=False)),
                ('id_familiar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospitalAPP.Familiar')),
                ('id_historia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospitalAPP.Historia_clinica')),
                ('id_medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospitalAPP.Medico')),
            ],
        ),
    ]
