# Generated by Django 3.0.7 on 2022-09-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalAPP', '0002_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='genero',
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1),
        ),
    ]
