# Generated by Django 3.0.7 on 2022-09-16 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalAPP', '0005_auto_20220915_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comment'},
        ),
    ]
